### PR TITLE
Enhancement: Raise minimum PHP version to PHP 7.1

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] raises the minimum PHP version from PHP 5.5 to PHP 7.1
* [x] updates `phpunit/phpunit`
* [ ] ...

💁‍♂️ For reference, see http://tinyletter.com/mwopzend/letters/zend-framework-community-news-for-the-week-of-2017-04-20.

### CODE REVIEW

**Comment by froschdesign** [comment]
@localheinz 
Develop branch!

**Comment by localheinz** [comment]
Ha, thank you, @froschdesign! Will take a look later!

**Comment by localheinz** [comment]
@froschdesign @weierophinney 

What do you think, should we also use

* strict types
* scalar type hints
* return type declarations

?

**Comment by froschdesign** [comment]
@localheinz 
>  - strict types
> - scalar type hints
> - return type declarations

- Void return types
- Nullable types
- "iterable" pseudo-type
- …

All features which simplify the code and make the interfaces more clear.

---

Btw. HHVM makes no sense if we allow failures on Travis.

**Comment by weierophinney** [comment]
This is a great start. However, per your question:

> What do you think, should we also use
> 
>     strict types
>     scalar type hints
>     return type declarations

The answer is yes. Adopting PHP 7.1 as the new minimum version should really only happen if we are going to make use of those features, particularly as they affect _consumers_ (extending classes or implementing interfaces means changes when we add these type hints).

I'll be merging #43 shortly, and issuing a new release when done. After that, rebase this based on the new status of develop, and let's see how far you can take it!

**Pull request merged**
